### ISSUE TITLE
Every video gives an unhandled error "YouTube-dl returned an empty object"

### ISSUE THREAD

**Issue by Mennaruuk** [jely2002/youtube-dl-gui#35] opened 2021-03-07 05:11 UTC
**Describe the bug**
All videos, including public ones, spit out the following error:
"This video is private, add a cookies.txt file to download private video's."

**To Reproduce**
1. Launch youtube-dl-gui
2. Paste the following video: https://www.youtube.com/watch?v=vJH28ICkCdU
3. See error

**Expected behavior**
This error should show only for private videos.

**Screenshots**
![image](https://user-images.githubusercontent.com/52135169/110229709-7a500680-7ed9-11eb-905e-8b4f2c57b451.png)

**Additional info (please complete the following information):**
 - **OS**: Ubuntu
 - **Application version**: 1.8.7

**Additional context**
Stay awesome.

**Comment by jely2002** [comment] 2021-03-07 12:28
Hi mennaruuk,

I tried reproducing the issue on my side. However everything was working fine here.
The app shows "This video is private, add a cookies.txt file to download private video's." when ytdl returns an invalid response. Usually this happens when the video is private, it may also happen when something is wrong with youtube servers,  your own connection or when the youtube-dl binary is not up to date. If you have disabled the binary auto-update enabling it may solve the issue. Otherwise I believe the issue will resolve itself.

Please let me know if the issue persists.

**Comment by Mennaruuk** [comment] 2021-03-20 04:48
To be honest, I played around with Ubuntu and reinstalled it. Even afterwards, after installing youtube-dl via pip3, and disabling binary auto-update, the same error pops up.

**Comment by jely2002** [comment] 2021-03-20 19:34
Great idea installing ytdl via pip, sadly my application is currently hardcoded to always use its own binary. So installing it through pip will have no effect.

I have uncovered another possible reason why it is still not working. YouTube could be ratelimiting your ip and or user agent combination, this can happen when you download quite a lot of videos in short succession. I have had it happen to myself too when I was busy developing 2.0.0. In 2.0.0 the right error gets displayed, but in the current version it shows the generic error `"This video is private, add a cookies.txt file to download private video's."` If you happen to have access to a VPN, try using a different IP and it should work again.

Hope I helped some more!

(About v2, I'm finishing the version up for release. All i gotta do is write some more unit tests and it can be released)

**Comment by Mennaruuk** [comment] 2021-03-20 19:37
Thanks, dude! This is amazing. I can't wait to download and use V2. This will be a huge milestone for yt-dl-gui!

**Comment by kazerniel** [comment] 2021-04-01 10:48
I have the same error message on public videos on Win10. I have auto update enabled.

**Comment by jely2002** [comment] 2021-04-02 10:57
Just adding a little update to this issue. I have found out that on various ubuntu based distributions youtube-dl will not work out of the box, because youtube-dl uses the python command. And this command does not work. 

Thus showing the "This video is private, add a cookies.txt file to download private video's." error in version 1.8.7. In version 2.0 it shows an unhandled error with the message "YouTube-dl returned an empty object".

A temporary workaround can be achieved by installing the `python-is-python3` package which makes the `python` command do the same as the `python3` command.

For more info check [this askubuntu question](https://askubuntu.com/questions/1037666/youtube-dl-python-not-found-18-04).

I will be looking for a permanent fix for this issue. Reopening it for now.

**Comment by kazerniel** [comment] 2021-04-02 17:18
> On win10 the same errors occur when the[ Microsoft Visual C++ 2010 Redistributable Package](https://www.microsoft.com/en-US/download/details.aspx?id=5555) is not installed on the system.
> Installing this redistributable may solve the issue @kazerniel is facing.

I tried installing it, but it says "A newer version of Microsoft Visual C++ 2010 Redistributable has been detected on the machine.
"

**Comment by jely2002** [comment] 2021-04-03 17:57
> > On win10 the same errors occur when the[ Microsoft Visual C++ 2010 Redistributable Package](https://www.microsoft.com/en-US/download/details.aspx?id=5555) is not installed on the system.
> > Installing this redistributable may solve the issue @kazerniel is facing.
> 
> I tried installing it, but it says "A newer version of Microsoft Visual C++ 2010 Redistributable has been detected on the machine.
> "

That means you already had that redistributable installed. So that was not causing the issue. Are you still having the issue with v2.0? If so, the only thing I can think of is antivirus software maybe messing with the app.

**Comment by kazerniel** [comment] 2021-04-09 09:06
Sorry, forgot to follow up on this, tried 2.0 for audio download just now, and it works like a charm! Thanks for putting together this great UI :)

**Comment by jely2002** [comment] 2021-04-19 23:06
Great to hear it is now working! I have added a little detection system so on linux it will look for a python install and use the one available. This means it will use the python3 or python2 command when the python command does not work. This feature will roll out in v2.1.0

Closing this for now.

**Closed by jely2002** 2021-04-19 23:06 UTC
Labels: bug

**Comment by xxtensazenxx** [comment] 2021-04-25 17:03
Sorry to re-open but it appears  Microsoft Visual C++ 2010 Redistributable is no longer available for download and was taken off Microsoft's website (maybe due to depreciation?) does anyone have a possible link to it? I've been looking around reddit, etc

![ss+(2021-04-25+at+01 03 17)](https://user-images.githubusercontent.com/30334231/116002215-a24d1380-a5c6-11eb-8df4-ac7c58feb2d5.png)

**Comment by jely2002** [comment] 2021-04-25 17:32
In my eyes it makes no sense for microsoft to remove this download. If this download is no longer available it will break backwards compatibility.

Guess you are in luck though, I still had it in my downloads folder. I can't provide a hash so you can check the file is legit, so you will have to trust me on this one.

Download:
[Microsoft visual C++ redistributable 2010 (Google Drive)](https://drive.google.com/file/d/1s5BE1ogVSEyeKi3WrhFxkcFHhXAP9r0j/view?usp=sharing)
SHA-1 hash: 372D9C1670343D3FB252209BA210D4DC4D67D358

**Comment by Mennaruuk** [comment] 2021-04-26 03:20
New link:
https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe
