### ISSUE TITLE
I got something wrong or error.

### ISSUE THREAD

**Issue by HeinKoZin** [jely2002/youtube-dl-gui#13] opened 2020-09-22 20:05 UTC
It stopped the youtube-dl binary is being updated, please wait.
I waited for so long but nothing happened.

**Comment by jely2002** [comment] 2020-09-23 07:58
Hi there,
I'm going to need a bit more information in order to help you.
What OS are you using? 
If you are using the latest version of youtube-dl-gui please press `ctrl-shift-d` or `cmd-shift-d`, and then in the newly opened window press on console. If you can send me what it says there it would be great.

**Comment by jely2002** [comment] 2020-09-30 12:23
I am unable to reproduce this issue without additional information, closing for now.  Feel free to re-open this issue when you are able to provide additional info.

**Closed by jely2002** 2020-09-30 12:23 UTC
Labels: bug
