### ISSUE TITLE
Unable to download playlists

### ISSUE THREAD

**Issue by subby2006** [jely2002/youtube-dl-gui#227] opened 2021-10-17 17:51 UTC
**Describe the bug**
Unable to download youtube or youtube music playlists

**To Reproduce**
1. Go to url bar
2. Add playlist
3. Wait until yt-dlg has finished gathering metadata
4. Playlist entry disappears

**Expected behavior**
The playlist should show with all songs/videos being shown in the download queue

**Screenshots**

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.3.1

**Additional context**
Playlist used: `https://youtube.com/playlist?list=PLwI2ixhBrYYPpCOQ8jIjRD3_Rgf2j5BCw`
The app spawns 32 processes of yt-dlg consuming about half of my cpu power
my luck with youtube downloaders is bad

**Comment by jely2002** [comment] 2021-11-13 18:53
Hello, thanks for the report. I'm unable to reproduce this on version 2.4.0, can you verify if it is fixed in this version?
If the process eats too much resources, try lowering the 'Max concurrent jobs' value in the settings.

**Closed by jely2002** 2021-11-13 18:53 UTC
Labels: bug, can't reproduce
