### ISSUE TITLE
Let user cut and download specific part of the video

### ISSUE THREAD

**Issue by ericmp33** [jely2002/youtube-dl-gui#253] opened 2021-12-03 20:24 UTC
## I'd like to crop the video to get only a specified range of it.
- For example, I input a video with length of 2 minutes and 30 seconds. Lets say I only want to get the video from the minute 1 to the minute 2. Would be nice to let us to crop it, so I don't download the start of it and neither the last part of it.

Thanks and awesome job!

**Comment by jely2002** [comment] 2022-02-02 14:54
Duplicate of #161.

**Closed by jely2002** 2022-02-02 14:54 UTC
Labels: feature request
