### ISSUE TITLE
'Show file in folder' and 'Open file' don't work on files with accents

### ISSUE THREAD

**Issue by aybe** [jely2002/youtube-dl-gui#166] opened 2021-08-31 03:31 UTC
**Describe the bug**

Both actions don't work on files with accents

**To Reproduce**
1. Download a video with accents on the name
2. Click on 'Show file in folder' does nothing
3. Click on 'Open file' shows an Explorer error

**Expected behavior**

Both of these actions should work.

**Screenshots**

![Open_Video_Downloader_2021-08-31_05-26-55](https://user-images.githubusercontent.com/1537591/131436998-8597964a-2596-45be-a38a-25e850cfee61.png)

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.3.0
 - Application type: installer

**Additional context**

Video with accents: https://www.youtube.com/watch?v=YqMu64zs_Jc

**Comment by jely2002** [comment] 2021-08-31 11:25
Thanks for reporting! This is a duplicate of #160. It has been fixed, the fix will be shipped with the next bugfix update. (2.3.1)

**Closed by jely2002** 2021-08-31 11:25 UTC
Labels: bug
