### ISSUE TITLE
Added Chinese language support

### ISSUE THREAD

**Issue by HyhBlazing** [jely2002/youtube-dl-gui#252] opened 2021-12-01 11:30 UTC
Add Chinese support, I am in China, so I hope to add Chinese UI support

**Comment by MusiCode1** [comment] 2022-01-31 22:16
I suggest using the [weblate.org](https://weblate.org/) platform,
In order to allow each user to translate the application into his language.

**Comment by jely2002** [comment] 2022-02-01 00:04
This is a duplicate of #154 and #89. Closing it as such.

**Closed by jely2002** 2022-02-01 00:04 UTC
Labels: feature request
