### ISSUE TITLE
Why after I create a new YouTube URL address task, the item disappears for at least one minute before it appears 

### ISSUE THREAD

**Issue by sojey** [jely2002/youtube-dl-gui#172] opened 2021-09-03 05:08 UTC
windows 10 x64 The latest version
ShadowsocksR-dotnet4.0
Open Video Downloader 2.3.0

I am Chinese user and I like this software very much. But when I add the YouTube URL address, click + as shown in the video, the added items will disappear after a few seconds, and the results will be displayed normally after about 1 to 3 minutes.

For details, please refer to https://drive.google.com/file/d/1h_FwgG_Ow4WMDLXRSBfbK2QAe7eE1XpB/view?usp=sharing

I am using version 2.3.0, no matter how I set it up, the result remains the same. But the download speed is close to the speed of the proxy I use, and this is not caused by network delays.

This situation greatly extends the download time and reduces the efficiency. I don't know if 2.3.1 is improved.

The proxy software I use is ShadowsocksR-dotnet4.0, and the software setting is 127.0.0.1:1081. The proxy works normally, and Open Video Downloader can also connect to YouTube to get it.

**Comment by jely2002** [comment] 2021-09-08 08:13
Hi sojey,

Thanks for reporting this. It definitely isn't supposed to do that, but sadly I wasn't able to reproduce this issue.

The only cause I can think of, is a very slow PC having trouble analysing the video metadata. 
Because when the video get's removed, the metadata gets applied, and a new video gets added with the metadata.
In that case there's nothing I can do to fix this, as the metadata needs to be analysed.

Closing this issue for now, as I don't see a clear cause for it in the code, and can't reproduce it.
Feel free to add more info to this issue, so it can be re-opened.

**Closed by jely2002** 2021-09-08 08:13 UTC
Labels: question, can't reproduce
