### ISSUE TITLE
youtubedl returned empty object

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#55] opened 2021-05-05 14:00 UTC
![image](https://user-images.githubusercontent.com/83282129/117152876-7f431080-adcb-11eb-93f0-d097b7f8189c.png)
![image](https://user-images.githubusercontent.com/83282129/117152897-82d69780-adcb-11eb-9e87-96c53fc668d5.png)
i put a new cookies.txt and everything
every alternate time i open the app this happens.
also when i pressed ctrl shift i it was blank nothing was showing.
also this issue resolves if u close the app and open it again

**Comment by trymeouteh** [comment] 2021-05-06 02:43
I get this too but the red error message says "Error Unhandled execption" but when I click on the show full error button it says "youtubedl returned an empty object"

**Comment by thaynos** [comment] 2021-05-06 05:26
> I get this too but the red error message says "Error Unhandled execption" but when I click on the show full error button it says "youtubedl returned an empty object"

exactly same

**Comment by thaynos** [comment] 2021-05-18 07:45
also when running v2.0.0 and v2.1.0 simuntaneously v2.1.0 shows empty object whereas v2.0.0 works fine

**Comment by jely2002** [comment] 2021-05-18 20:56
I have identified another possible cause of this issue. This fix will ship in v2.1.2. Because I am unable to reproduce this issue locally, I would appreciate it if any of you could tell me if the issue persists in version v2.1.2.

**Comment by thaynos** [comment] 2021-05-19 07:33
thanks for your hard work dude i appreciate it a lot idk much about programming and code so i had to find a gui for youtube-dl and your app is perfect(except for some flaws but that should be expected)! i wish i could donate but my mom wont allow D: .

**Comment by jely2002** [comment] 2021-05-19 23:12
Hi thaynos,

I think I have identified the issue, for real this time. Could you try to install the [Microsoft visual C++ redistribution 2010](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe) on your computer. In my testing, not having this redistribution installed gives the "empty object" or "please report this issue" error. While having it installed youtube-dl-gui works perfectly.

Please let me know if this issue keeps happening eventhough you installed the [Microsoft visual C++ redistribution 2010](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe).

**Comment by thaynos** [comment] 2021-05-21 11:06
ohhhh idts i have it installed cuz im using a guest pc rn and installing the c++ package needs admin :( . thx a lot tho.

**Comment by jely2002** [comment] 2021-05-30 19:55
Closing for now as I have patched the root cause of this problem. Will keep monitoring for further errors regarding this.

**Closed by jely2002** 2021-05-30 19:55 UTC
Labels: bug

**Comment by Dmitry-Dimitrov** [comment] 2022-05-27 21:01
Jely2002, I have the same problem as the person who created this issue, but i inastalled Microsoft visual C++ redistribution 2010? and it didnt help. Please, help. I use win10 x64. Sorry for my english.
