### ISSUE TITLE
[Win64] Error 01 Postprocessing

### ISSUE THREAD

**Issue by Jacekun** [jely2002/youtube-dl-gui#246] opened 2021-11-22 09:28 UTC
Error happened after downloading video/audio and trying to merge metadata to the output file.

**To Reproduce**
1. Download Portable version for Windows. [Link here](https://github.com/jely2002/youtube-dl-gui/releases/download/v2.4.0/Open-Video-Downloader-2.4.0-portable.exe)
2. Paste youtube url for video with thumbnail.
3. Click download

**Expected behavior**
Should merge video/audio file properly.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/54625750/142835775-920e06be-18c9-4e50-adb4-88eeea0ccabe.png)

**Additional info (please complete the following information):**
 - OS: [Windows 10 21H1]
 - Application version [e.g. 2.4.0]
 - Application type [portable,]

**Additional context**
Solved this issue by replacing ``v4.2.1`` (auto downloaded) ``ffmpeg`` and ``ffprobe`` with ``v4.4.1`` [downloaded from here](https://www.gyan.dev/ffmpeg/builds/).

Should update builds to point to newer ffmpeg release.

**Comment by jely2002** [comment] 2021-11-22 12:40
Thanks for the report. This is a duplicate of #236. I will be closing it as such.

**Closed by jely2002** 2021-11-22 12:40 UTC
Labels: bug
