### ISSUE TITLE
Set same quality for all videos

### ISSUE THREAD

**Issue by MohamedAtef25** [jely2002/youtube-dl-gui#111] opened 2021-06-20 19:36 UTC
**Is your feature request related to a problem? Please describe.**
I currently want to download some links with the same video quality e.g. 360p but I have to go through each video and select the same quality which is very time consuming.

**Describe the solution you'd like**
I would like to have the ability to select the download quality from the settings to be applied for all videos e.g. 360.

**Additional context**
Thanks in advance.

**Comment by jely2002** [comment] 2021-06-20 22:48
Hi Mohamed,

This issue is a duplicate of #52. That issue also calls for a way to set all videos to a specific quality.
I will be closing this issue, as this will be added through #52.

If you have any other questions please let me know.

**Closed by jely2002** 2021-06-20 22:48 UTC
Labels: feature request
