### ISSUE TITLE
Missing feature (from Youtube-dl) Download set number of videos from Playlist

### ISSUE THREAD

**Issue by ethanccss** [jely2002/youtube-dl-gui#230] opened 2021-10-29 22:52 UTC
In the old youtube-dl gui you can set it to only download a range of videos from a playlist, instead of the entire thing.

This is immensely useful for people like myself who constantly update playlists over the year and want to only download the new additions, which is usually the most recent 10-20 videos. So in the old program Id tell it to download from video 1-20 then stop.

Please add this simple feature! I cant switch till then.

**Comment by jely2002** [comment] 2021-10-29 23:09
Thanks for the feature request, I agree that this would be a good feature.

I believe this is a duplicate of issue #113. As such I will be closing this issue, but rest assured I will try to add this when possible.

**Closed by jely2002** 2021-10-29 23:09 UTC
