### ISSUE TITLE
random network throttling

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#51] opened 2021-05-03 12:22 UTC
![image](https://user-images.githubusercontent.com/83282129/116875187-90551b80-ac2b-11eb-85c3-c84cf717eaff.png)
i was downloading stuff from my watch later list but then for soem of them it started goign down to the kbps but if i tried to download the same video again manually it goes back to normal

**Comment by jely2002** [comment] 2021-05-03 16:59
Hi thaynos,
The download speed is just an indication and is not always too accurate. I strongly believe this drop in speed was not caused by this application, and had more likely something to do with YouTube. Closing the issue for now. If someone else has this problem too, feel free to comment and I might reopen sometime.

**Closed by jely2002** 2021-05-03 16:59 UTC
Labels: bug, wontfix
