### ISSUE TITLE
Application can't open downloaded videos with Korean names.

### ISSUE THREAD

**Issue by Oppa-YA** [jely2002/youtube-dl-gui#163] opened 2021-08-29 19:52 UTC
**Description of the bug**

Button "Show in the folder" doing nothing. Button "Open file" giving only error "Windows cannot find "filename.webm""

The **problem** of the app is that it's downloading videos with partially Korean and English in names and save them with full and correct name but when it trying to open them it searching only for English part of the name (without Korean part of the name, just deleting it from search request) and can't find them.

**Screenshots**

First screenshot showing the _correct_ downloaded file name in forder:

![Screenshot 2021-08-29 223208](https://user-images.githubusercontent.com/11776599/131263456-0cd59e09-e3c5-431c-bea0-31c67dc1f51b.png)

Second screenshot showing the _incorrect_ file name that app is searching for and can't find in folder (it just searching for English part of the name ignoring the Korean part of the name):

![Screenshot (3729)](https://user-images.githubusercontent.com/11776599/131263417-5c0210d7-894a-4db4-8107-49aa4d323fdc.png)

**Additional info**
 - Source video with Korean name to check the bug: https://www.youtube.com/watch?v=gkkkGM3BMRY
 - OS: Windows 10 (English)
 - Application version v2.3.0
 - Application type: Installer

**Comment by jely2002** [comment] 2021-08-29 20:48
This is a duplicate of #160. It has been fixed, and it will be released on the next bugfix update.
I can confirm that opening the video you mentioned works with the fix.

**Closed by jely2002** 2021-08-29 20:48 UTC
Labels: bug
