### ISSUE TITLE
Problem with big files

### ISSUE THREAD

**Issue by flopezre** [jely2002/youtube-dl-gui#128] opened 2021-07-09 22:49 UTC
**Describe the bug**
Problem with big files, i try to downlead this video (https://www.youtube.com/watch?v=xgEZ58sBQxs) (ASMR from Russia).
1.43:15 with 1080p60 maybe the size is 2.0GB?

**To Reproduce**
1. The metadata of the video say 97 MB

**Expected behavior**

**Screenshots**
![Inkedbug_LI](https://user-images.githubusercontent.com/4932575/125142189-205c8900-e0e5-11eb-85a2-bd59d8c74a4c.jpg)

![gif](https://user-images.githubusercontent.com/4932575/125142659-46cef400-e0e6-11eb-87eb-f59743039145.gif)

**Additional info (please complete the following information):**
 - OS: Windows 10 21H1
 - Application version 2.2.2

**Comment by jely2002** [comment] 2021-07-14 08:57
Hi Fabian,

I'm unable to reproduce this issue on my side. Although it appears that it is showing the `audio only` size. While you have selected the `video + audio` option. I am unable to fix this as I can't reproduce this, I tried really breaking everything but I couldn't reproduce.

Closing this issue for now. If it happens again you can always reopen this issue. Preferably with what you were doing to make that happen.

**Closed by jely2002** 2021-07-14 08:57 UTC
Labels: bug

**Comment by flopezre** [comment] 2021-07-14 17:57
Hello, i try manual calculate and works:
![gif](https://user-images.githubusercontent.com/4932575/125669889-9b118519-80a1-43e0-880c-61baa1b51d66.gif)
