### ISSUE TITLE
Download does not reach maximum speed and freezes during the process

### ISSUE THREAD

**Issue by rogerwindberg** [jely2002/youtube-dl-gui#117] opened 2021-06-24 20:01 UTC
Download does not reach maximum speed and freezes during the process.

Below is a video I made demonstrating the problem:

<a href="https://www.youtube.com/watch?v=BTFHoZ4YXIQ">YouTube DL GUI - Speed Test</a>

Below is an image showing that my internet is stable:

<a href="https://www.speedtest.net/result/11628495210"><img src="https://www.speedtest.net/result/11628495210.png" width="50%"/></a>

OS: Windows 10 64-bit
Version: 2.2.1

**Comment by jely2002** [comment] 2021-06-28 20:25
This has to do with youtube limiting your speed. Not per se with my application. However it could be fixed by using an external download tool such as Aria2C so it can set up multiple connections. Because of this I will be marking this a duplicate of #49.

**Closed by jely2002** 2021-06-28 20:25 UTC
Labels: bug

**Comment by jely2002** [comment] 2021-07-03 18:45
This may have to do with YouTube throttling DASH video downloads. This was an issue before, it probably came back.
Here's a link with an explanation of what is happening: https://github.com/ytdl-org/youtube-dl/issues/15271
