### ISSUE TITLE
Downloader GUI not remembering download location

### ISSUE THREAD

**Issue by bhargu** [jely2002/youtube-dl-gui#119] opened 2021-06-30 16:56 UTC
Every time I open the app, the "download location" reverts to the Windows 10 default download location (<HOME>\Downloads).

How can I make the app remember the last download location? Without this, using the app becomes difficult. If you don't remember to switch the location before downloading, it becomes annoying.

**Comment by jely2002** [comment] 2021-06-30 18:18
Hi bhargu,
This feature has been implemented, but hasn't been releases yet. This is thus a duplicate of #109.
I suspect I will release the update with this fix somewhere this week.

Thank you.
I you have any other questions feel free to ask.

**Closed by jely2002** 2021-06-30 18:18 UTC
