### ISSUE TITLE
Tor Proxy 

### ISSUE THREAD

**Issue by EsmaeelK** [jely2002/youtube-dl-gui#93] opened 2021-05-31 19:11 UTC
Hi jely

I Think its not work with Tor Proxy

![YouTube_Downloader_GUI_w6smPyMEL0](https://user-images.githubusercontent.com/34475028/120232745-12952780-c24c-11eb-99ca-6cdb7b57bcf0.png)

**Comment by jely2002** [comment] 2021-05-31 19:42
Before anything else, that is not a tor proxy IP. That is your [localhost](https://en.wikipedia.org/wiki/Localhost) IP and that will of course not work.

**If you do use a valid proxy IP (not localhost):**
Either the proxy is not working or responding fast enough, this is often the case with Tor/free proxies as they tend to be slow and unreliable. Thus the connection times out and it doesn't work.

For more info about what to put in the proxy box take a look at the [documentation of youtube-dl about proxying](https://github.com/ytdl-org/youtube-dl#network-options).

In any case this is not a bug in this app. Will close this issue as it is impossible to investigate from my end.

**Closed by jely2002** 2021-05-31 19:42 UTC
Labels: bug
